version: '3.9'

services:
  bs-note:
    container_name: bs-note
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - '127.0.0.1:3002:3002'

    restart: unless-stopped

    read_only: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    user: '1000:1000'
